[package]
name = "spqr-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
libcrux-hkdf = "0.0.6"
libcrux-hmac = "0.0.6"
libcrux-ml-kem = { version = "0.0.8", default-features = false, features = ["incremental", "mlkem768"] }
libcrux-sha3 = "0.0.8"
# reed-solomon-simd currently, need to consider alternative for wasm
g2p = "1.2.2"
rand = "0.9.3"
rand_core = "0.9.5"

[features]
default = ["std"]
std = []